# Generated by Django 4.2.2 on 2023-11-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_district_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='district',
            new_name='District',
        ),
    ]
