# Generated by Django 4.2.2 on 2023-11-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_rename_district_branch_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='District',
            new_name='district',
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('materials_provide', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.branch')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.district')),
            ],
        ),
    ]
