# Generated by Django 4.2.2 on 2023-11-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0020_delete_customer_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
