# Generated by Django 4.2.2 on 2023-11-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0021_alter_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
