# Generated by Django 4.2.2 on 2023-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0024_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
